### ISSUE TITLE
different starting point and orientation between odom and raw_odom

### ISSUE THREAD

**Issue by hwscut** [berndpfrommer/tagslam_test#3]
when running example 11, I want to compare the trajectory between /tagslam/odom/body_rig and /tagslam/raw_odom/body_rig.
But  the starting point of the two trajectory is different, they has some offsets. And the orientations have 90 degrees difference.
How to slove the problem?

**Comment by berndpfrommer** [comment]
You need to also publish the transform between the vio's global reference frame (called "vision") and the global "map" reference frame that tagslam is using. The following transform is just a rough ball park, adjust the numbers so it looks good.

```
rosparam set use_sim_time true
rosrun tf static_transform_publisher -1.12625 0.4480 0.832 1.605 0 0 map vision 100
rosbag play --clock tag_detections.bag reference.bag

```
Now in rviz, set the global fixed frame to "map", and visualize the /tagslam/odom/body_rig and "/fla/vio/odom" topics.

**Comment by hwscut** [comment]
I  have to know the transform from vision to map, before running all tagslam codes?
so why not provide the transform in codes, instead of manual conversion.

```
 void
  OdometryProcessor::process(Graph *graph, const OdometryConstPtr &msg,
                             std::vector<VertexDesc> *factors) {
    auto msg2 = *msg;
    msg2.header.frame_id = "map";
    pub_.publish(msg2);
```
In these codes, just simply replace the frame_id with "map", and not  contain conversion

**Comment by berndpfrommer** [comment]
The VIO has its own world reference frame ("vision"), which depends on how the robot is oriented at start. Usually the VIO's global reference frame is arbitrarily set to be z-axis along the direction of gravity, then x-axis pointing 'forward' (whatever that is on the robot), and y-axis perpendicular to x and z. This means that when you run your VIO several times, with different starting orientation of the robot, you will get a different trajectory, i.e. x and y can be very different.
In contrast, TagSLAM's global reference frame ("map") is determined implicitly by the static body poses, and the tag poses (at least one necessary!) relative to that body.
Because the VIO's ("vision") frame is oriented differently for every run, it cannot be hard coded, but must be fitted to each sequence separately.
However, if you feed the VIO into TagSLAM, you don't have to know the map-to-vision transform. Why? Because TagSLAM only operates on odometry *differences*, i.e in pose deltas. It never uses the absolute VIO pose. In fact, until TagSLAM sees the first tag with known global position, it does not use any of the VIO updates, but rather stores them in case they become useful later. It cannot use them at first because it doesn't know the starting point. Only when it sees the first tag, that's when the VIO updates become useful: now TagSLAM determines its global position, and works it's way *back* to the beginning of time, using the VIO updates.
You can observe that if you run TagSLAM, and it only sees a Tag fairly late in the run. Rviz will not show you any VIO updates until the tag comes into view. You will have to issue a "replay" service call to even see the path that is earlier than the first tag.

**Comment by hwscut** [comment]
Thanks, your explanation has benefited me a lot.
